### ISSUE TITLE
Changes to render method

### ISSUE THREAD

**Issue by zonzujiro** [turchak/weather-app#1]
https://github.com/turchak/weather-app/blob/4aa3e194f4c9b8029e5c274f5401c9cef6331d17/src/js/components/forecast.js#L12

You can make `day` as method, as example `createDayElement`, of this class and then use it like this:

```js
render() {
  return this.props.week.data.map(this.createDayElement)
}
```

**Comment by turchak** [comment]
This is a good idea.  Now it works with more clean code. Thanks
